export { default as Footer } from './Footer';
export { default as Navbar } from './Navbar';
export { default as Welcome } from './Welcome';
export { default as Login } from './Login';
export { default as Home } from './Home';
export { default as ProfileSetup } from './ProfileSetup';
export { default as Profile } from './Profile';
export { default as EditProfile } from './EditProfile';
export { default as UploadCertfiicate } from './UploadCertfiicate';